# 在这里编写springboot的配置信息
server:
  port: 8080
  context-path: /
  application:
    name: dubbo-consumer
management:
  port: 8081
dubbo:
  application:
    id: dubbo-consumer
    name: dubbo-consumer
  protocol:
    id: dubbo
    name: dubbo
    port: 20880
  registry:
    id: my-registry
    address: zookeeper://172.16.4.114:2181

